apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Uncomment to enable via app-of-apps pattern
  # - step-01-gpu-and-prereq.yaml
  # - step-02-rhoai.yaml
  # - step-03-private-ai.yaml
  # - step-04-model-registry.yaml
  # - step-05-llm-on-vllm.yaml
  # - step-06-private-ai-playground-maas.yaml
