apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Uncomment to enable via app-of-apps pattern
  # - step-01-gpu-and-prereq.yaml
  # - step-02-rhoai.yaml
  # - step-03-private-ai.yaml
