apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Additional ServiceMonitors used by Step 07 dashboards.
# These complement the ServiceMonitors auto-created by KServe for InferenceServices.

resources:
  - servicemonitor-llmd-router.yaml
  - servicemonitor-llmd-workload.yaml


