# Custom Metrics Autoscaler (CMA) Operator
#
# Provides KEDA-based autoscaling for Kubernetes workloads.
# Required for SLO-driven autoscaling of llm-d workloads.
#
# Based on: https://github.com/redhat-cop/gitops-catalog/tree/main/openshift-custom-metrics-autoscaler
# Ref: https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/nodes/index#nodes-cma-autoscaling-custom

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-keda

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - kedacontroller.yaml

