apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Model Registry Instance
# Deployed in rhoai-model-registries namespace (operator-managed)

resources:
  - db-credentials-secret.yaml
  - model-registry.yaml
