apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Model Registry Instance
# Deployed in redhat-ods-applications for global dashboard visibility

resources:
  - db-credentials-secret.yaml
  - s3-credentials-secret.yaml
  - model-registry.yaml

