# OpenShift Pipelines Operator Installation
# ============================================================================
# Installs Red Hat OpenShift Pipelines (Tekton) for CI/CD pipelines.
#
# Channel: latest
# Version: 1.20.2
#
# Ref: https://github.com/redhat-cop/gitops-catalog/tree/main/openshift-pipelines-operator
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines/1.20
# ============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - subscription.yaml

